sudo: required
language: ruby
services:
  - docker
install: true
script:
  - docker build -t procube/jwt-nginx-lua .
  - mkdir -p /tmp/RPMS/x86_64
  - sudo chown 111:111 -R /tmp/RPMS
  - docker run -it --rm --name jwt-nginx-lua -v /tmp/RPMS:/home/builder/rpmbuild/RPMS procube/jwt-nginx-lua
  - (cd /tmp;tar czf - RPMS) > $TRAVIS_BUILD_DIR/jwt-nginx-lua.tar.gz
deploy:
  provider: releases
  api_key:
    secure: "E6eMCF++x0QAhpDlZK2SXbOZH/aX9XvEiHtOIVgU+3Bbrcg5WVqqJESVJo9jDlcYsdBJmzRA3k2kxch3Jj/+WgiF5G8fRoYx9HSLaaTkQU5Yz9IiZl71DmbiKGjQ8SCkgbgLq+y6HaqdDTo54n6NPmSlRMVCIGHklPQRNCvdyowGtVcKiT7+GdRbdv5uuDZEN/PIJKxbLKo3n5mvqvA8mFCtASGg9VxR0uxIv0FJh5Ipm/tcsJRVtHv+6/9VyCMhRjlsjpxUsbyPsRpe/16qWRjSMtJM6430anRwE0vi3NN5pZc6+NwBimMLBT6d6CthSoeOw1WEIYxUE04dVBIeuhm7SlnWkDrRGY4ols8UVYuW76yZ4f/gNFfOGYjmZ0QvrK7ma0UyfLRQtZx+ZIwLtsgWibvGODdMU+ToSS/DbMXcx24oCrMKNr+7YRQCA8olm/a0F6eYeOr0695kmIM54divh9xkF3HmegEp/U7aR6Kn0ahv8TyOyJKjP8d2MZLA2zS9PGIzgchlq7RVceFNl9/2h8EiEBRbr8+VnUNK4M+tvu1gCcJ1k8tS7sqFdmt14smWO3p1mmRG/+hHcd3K3uAz4SngXGxZS3n1uGTsSZHzQOOjnIsW+SXVllZUnLaIUi0R3jmon40Qpz6JmV5T0lNi+7aaF364P8Ii5KdMJtY="
  file: jwt-nginx-lua.tar.gz
  overwrite: true
  skip_cleanup: true
  on:
    repo: procube-open/jwt-nginx-lua
    tags: true
